version: 2.1

orbs:
  node: circleci/node@2.0.3

commands:
  setup:
    steps:
      - checkout
      - node/install:
          node-version: 12.16.3
          install-yarn: true
      - run:
          name: Versions
          command: |
            node -v
            npm -v
            yarn -v
      - run:
          name: Set env variables
          command: |
            if [ ${CIRCLE_BRANCH} = master ]; then
              mv project ctodo
              echo "export PROJECT_NAME=ctodo" >> $BASH_ENV
              source $BASH_ENV
            else
              mv project stg-ctodo
              echo "export PROJECT_NAME=stg-ctodo" >> $BASH_ENV
              source $BASH_ENV
            fi
            echo $PROJECT_NAME
      - node/install-packages:
          app-dir: ~/${PROJECT_NAME}
          pkg-manager: yarn
          cache-key: yarn.lock

jobs:
  build:
    executor:
      name: node/default
      tag: 12.16.3
    steps:
      - setup
      - run:
          name: build
          command: yarn build
  deploy:
    executor:
      name: node/default
      tag: 12.16.3
    steps:
      - setup
      - run:
          name: deploy to now
          command: |
            cd ~/project
            yarn deploy:production

workflows:
  version: 2
  now_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
