version: 2.1

orbs:
  node: circleci/node@2.0.3

commands:
  setup:
    parameters:
      now-project:
        type: string
        default: stg-ctodo
    steps:
      - checkout
      - node/install:
          node-version: 12.16.3
          install-yarn: true
      - run:
          name: Versions
          command: |
            node -v
            npm -v
            yarn -v
            ls -l
            pwd
      - node/install-packages:
          app-dir: ~/<< parameters.now-project >>
          pkg-manager: yarn
          cache-key: yarn.lock
      - run:
          name: Move project dir
          command: |
            pwd
            ls
jobs:
  deploy:
    working_directory: ~/stg-ctodo
    executor:
      name: node/default
      tag: 12.16.3
    steps:
      - setup
      - run:
          name: deploy to now
          command: |
            yarn deploy

workflows:
  version: 2
  now_deploy:
    jobs:
      - deploy