version: 2.1

orbs:
  node: circleci/node@2.0.3

commands:
  setup:
    steps:
      - checkout
      - node/install:
          node-version: 12.16.2
          install-yarn: true
      - run:
          name: Versions
          command: |
            node -v
            npm -v
            yarn -v
      - node/install-packages:
          pkg-manager: yarn
          cache-key: yarn.lock

jobs:
  build:
    executor: node/default
    steps:
      - setup
      - run:
          name: build
          command: yarn build
  deploy:
    executor: node/default
    steps:
      - setup
      - run:
          name: deploy to now
          command: yarn deploy:production

workflows:
  version: 2
  now_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
